#!/bin/sh -e

chown nobody ${AUTOPKGTEST_TMP}

cd ${AUTOPKGTEST_TMP} && \
    ls -la && \
    echo "python3 -m twisted.trial --temp-directory=${AUTOPKGTEST_TMP}/_trial_temp --reactor=default --reporter=verbose -e twisted" | su -s /bin/sh nobody
